### ISSUE TITLE
Autoprefixer for IE 10-11 support

### ISSUE THREAD

**Issue by ai** [sylvainpolletvillard/postcss-grid-kiss#12]
Let’ remove old hacks and use Autoprefixer Grid for IE 10-11 support. New Autoprefixer with `grid: true` supports even `grid-gap` and `grid-template-area`.

**Comment by sylvainpolletvillard** [comment]
Autoprefixer only works for IE10-11 using the obsolete Grid specification and `-ms-` vendor prefixes. What about all the other browsers that use the current grid-kiss fallback, like Safari 6 - 10 and older versions of Chrome/FF ?

**Comment by ai** [comment]
IT doesn’t help them. But should we care about them? ;)

**Comment by sylvainpolletvillard** [comment]
Of course I care. According to caniuse, Grid is supported on 84.9% browsers + 3.2% with autoprefixer for IE10-11, and calc() is supported on 94% browsers. So autoprefixer covers 3.2% while the current fallback covers over 9% of users.

If some developers don't care about losing these 6% (!!!) potential users, they can always disable the fallback and use autoprefixer with the grid option.

**Comment by ai** [comment]
Good point :+1:

**Comment by sylvainpolletvillard** [comment]
Okay, if we agree then I think I can close this
