### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by jascodes** [sylvainpolletvillard/postcss-grid-kiss#13]
Absolutly loved your project. I use react-spring for animations. I was wondering can I compile at runtime or come up with some trick so the animations will work even with the fallback code?

Any thoughts on this?

PS: Love your OCR idea, myself worked in computer vision for 3yrs; I think if we use machine learning we can go step futher to read the titles as well :)

Thx

**Comment by sylvainpolletvillard** [comment]
Hi,

I don't know about react-spring, but when using CSS transitions, it should also work for fallback code if the transition is set for `all` properties, and not specifically for some CSS Grid properties. Maybe I could help you better if fou provide some example code.

I'm really interested by your skills in computer vision. I tried some experiments with Tesseract, OpenCV and Google Cloud Vision but I did not manage to read both the grid and the text. If you can do it, that would be really cool and bring some attention to this project.

**Comment by jascodes** [comment]
Awesome, thx for writing back. I was bit swamped with work during this week. In my next project I will try out your plugin. My plan is to actually use your code to do interpolation with react-spring for animations. My use cases might resemble something like this https://zenart.com/industries/finance

I will follow up on this in some time.

Thx

**Comment by sylvainpolletvillard** [comment]
I'm closing the issue but any help with computer vision is still welcome
