### ISSUE TITLE
Option to change grid-kiss property

### ISSUE THREAD

**Issue by YPetremann** [sylvainpolletvillard/postcss-grid-kiss#25]
Hi! 👋 

Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `postcss-grid-kiss@3.0.3` for the project I'm working on.

I added a property option that permit to change the default "grid-kiss" with "grid-template-kiss" which is more compliant with prettier

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/postcss-grid-kiss/lib/main.js b/node_modules/postcss-grid-kiss/lib/main.js
index cf45395..1bc08ac 100644
--- a/node_modules/postcss-grid-kiss/lib/main.js
+++ b/node_modules/postcss-grid-kiss/lib/main.js
@@ -13,6 +13,7 @@ const
 	getFallback = require("./fallback");
 
 const DEFAULTS_OPTIONS = {
+	property: "grid-kiss",
 	optimize: true
 }
 
@@ -30,7 +31,7 @@ module.exports = function (options) {
 	return {
 		postcssPlugin: 'postcss-grid-kiss',
 		Declaration: {
-			"grid-kiss": (decl, { result, Rule, AtRule }) => {
+			[options.property]: (decl, { result, Rule, AtRule }) => {
 				const
 					{ rows, cols, zones, rowIndexes, colIndexes } = parse(decl, options),
 					grid = { props: new Map, rule: decl.parent },
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sylvainpolletvillard** [comment]
Should it be a patch for prettier instead ? I don't see how grid-template-kiss is more compliant, both are non standard properties.

**Comment by sylvainpolletvillard** [comment]
Interesting choice from Prettier team. It comes from here: https://github.com/prettier/prettier/blob/b429cee27367ceed1d276271f94c13672c09660b/src/language-css/printer-postcss.js#L524

In that case, I wonder if I should add an alias for "grid-template-kiss", no configuration needed. That would be helpful for all Prettier users, and documented.

**Comment by sylvainpolletvillard** [comment]
Added `grid-template-kiss` as an alias in v3.1.0. No configuration needed 👍
