### ISSUE TITLE
Use -ms- grid for IE fallback

### ISSUE THREAD

**Issue by ai** [sylvainpolletvillard/postcss-grid-kiss#5]
Technically, IE was the first browser, which support Grid :). His `-ms-` syntax is very limited. But I found that many features could be implemented. For example, `grid-template-areas` is not in `-ms-`, but it is just syntax sugar — you could use different grip properties to set grid child position.

@sylvainpolletvillard do you think it is possible to fallback your awesome plugin for IE using `-ms-` gird syntax?

**Comment by sylvainpolletvillard** [comment]
Yeah I already tried to make it work on Edge with the old specification but without `grid-template-areas` its very complicated.

But guess what ? I just released 0.3.0 with uses `position:absolute` and `calc()` to make it work on (almost) all browsers. Check it out :smile:

https://cdn.rawgit.com/sylvainpolletvillard/postcss-grid-kiss/0.3.0/playground/index.html

**Comment by ai** [comment]
Yeap, `fallback` is so awesome!

IE 11 is still 10 %. Too big to loose users because of this plugin.

I know that it is hard without `grid-template-areas`. But maybe you could try. Image how awesome plugin become (“CSS only CSS Grid Layout polyfill with even better syntax!!!”) ;).

**Comment by ai** [comment]
If you need some support, I could promote this issue in PostCSS twitter and my company’s [Cult of Martians](http://cultofmartians.com/).

**Comment by sylvainpolletvillard** [comment]
What about a `fallback:"only"` option which will only keep the fallback code ? Then it will only require `calc()`, which is supported even by IE9. And it's much simpler :wink:

**Comment by ai** [comment]
Hm. Sure.

**Comment by sylvainpolletvillard** [comment]
I put this on the list for v0.4. If the next release could work on IE9, this would be awesome
